### ISSUE TITLE
stdout and stderr mixed in secrethub run

### ISSUE THREAD

**Issue by SimonBarendse** [secrethub/secrethub-cli#196]
### Encountered Behavior
When the subcommand of `run` writes to both `stdout` and `stderr` and secret masking is enabled, the output of stdout and stderr is mixed, resulting in potentially unreadable output.

When wrapping [this example](https://goplay.space/#-HWl4aV2FYY) in `secrethub run` the output can be any of these:
`123`
`213`
`132`

### Expected Behavior
When the subcommand writes to both `stdout` and `stderr`, the order in which is written to the two of these is preserved.

When wrapping [this example](https://goplay.space/#-HWl4aV2FYY) in `secrethub run` the output is always `123`.

**Comment by mackenbach** [comment]
Wow nice catch! Quesstion I have is: the terminal may show both `stdout` and `stderr` in one output stream, but does it give guarantees as to the order of output? Because the order of `stdout` and `stderr` themselves is preserved, just not when they're mixed.

In other words, is not preserving the order an issue or does it fall within the expected behavior of the terminal (when you mix both output streams to one)?
